version: "3.9"

services:
  database:
    image: postgres:15
    container_name: basepaths-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basepaths
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/initialization:/docker-entrypoint-initdb.d
    networks:
      - basepaths-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/basepaths
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - database
    networks:
      - basepaths-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - basepaths-network

volumes:
  db_data:

networks:
  basepaths-network: