name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: basepaths_test
        ports: [5432:5432]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout Branch
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x backend/gradlew

      - name: Backend Build
        run: |
          cd backend
          ./gradlew clean build --no-daemon

      - name: Backend Tests
        run: |
          cd backend
          ./gradlew test jacocoTestReport --no-daemon
      
      # Upload reports as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/build/reports/jacoco/test/html

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --coverage

      - name: Install Frontend for Cypress
        run: npm ci

      - name: Start Backend
        run: |
          cd backend
          ./gradlew bootRun &

      - name: Start Frontend
        run: |
          cd frontend
          npm run preview &
        shell: bash
      
      - name: Wait for services
        run: sleep 120

      - name: Run Cypress
        run: npx cypress run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypres/videos